# Generated by Django 6.0.5 on 2026-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='type',
            field=models.CharField(default='Fresher', max_length=50),
        ),
    ]
