# Generated by Django 6.0.5 on 2026-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_alter_job_seeker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='category_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
