# Generated by Django 6.0.5 on 2026-06-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_job_seeker_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('skills', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.recruiter')),
            ],
        ),
    ]
