# Generated by Django 6.0.5 on 2026-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 Year'), ('1-1.5', '1-1.5 Years'), ('1.5-2', '1.5-2 Years'), ('2-3', '2-3 Years'), ('3-4', '3-4 Years'), ('4-5', '4-5 Years'), ('5-6', '5-6 Years'), ('6-7', '6-7 Years'), ('7-8', '7-8 Years'), ('8-9', '8-9 Years'), ('9-10', '9-10 Years'), ('10-11', '10-11 Years'), ('11-12', '11-12 Years'), ('12-13', '12-13 Years'), ('13-14', '13-14 Years'), ('14-15', '14-15 Years'), ('15-16', '15-16 Years'), ('16-17', '16-17 Years'), ('17-18', '17-18 Years'), ('18-19', '18-19 Years'), ('19-20', '19-20 Years'), ('20+', '20+ Years')], max_length=20),
        ),
    ]
