# Generated by Django 6.0.5 on 2026-06-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_alter_job_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Job.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='clogo',
            field=models.ImageField(blank=True, null=True, upload_to='job_logo/'),
        ),
    ]
