# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_alter_job_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category',
            field=models.CharField(choices=[
                ('Internship', 'Internship'),
                ('Junior Developer', 'Junior Developer'),
                ('Senior Developer', 'Senior Developer'),
                ('Fresher', 'Fresher'),
                ('AI/ML Intern', 'AI/ML Intern'),
            ], max_length=100),
        ),
    ]
