# Generated by Django 6.0.5 on 2026-06-24 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(null=True, upload_to='')),
                ('Date', models.DateField()),
                ('Job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.job_seeker')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.job')),
            ],
        ),
    ]
