# Generated by Django 6.0.5 on 2026-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0011_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
