# Generated by Django 6.0.5 on 2026-08-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0014_portalrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
