# Generated by Django 6.0.5 on 2026-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0016_recruiter_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer'), ('Fresher', 'Fresher'), ('AI/ML Intern', 'AI/ML Intern'), ('Software Development', 'Software Development'), ('Web Development', 'Web Development'), ('Data Science & AI', 'Data Science & AI'), ('Cloud & DevOps', 'Cloud & DevOps'), ('Cybersecurity & IT Support', 'Cybersecurity & IT Support'), ('Human Resources', 'Human Resources'), ('Marketing & Sales', 'Marketing & Sales'), ('Finance & Accounting', 'Finance & Accounting'), ('Operations & Administration', 'Operations & Administration'), ('Design & Content', 'Design & Content')], max_length=100),
        ),
        migrations.AlterField(
            model_name='portalrating',
            name='display_name',
            field=models.TextField(),
        ),
    ]
